### ISSUE TITLE
Save & Reload Functionality

### ISSUE THREAD

**Issue by tehalexf** [matloff/ShinyImage#2]
Add the ability for the user to pick up where they left off.

TODO: Perhaps autosave in the present working directory?

**Comment by matloff** [comment]
On Sat, Mar 11, 2017 at 09:08:07PM -0800, Alexander Fu wrote:

> Add the ability for the user to pick up where they left off.

Great, I will try it out.

Any progress with Shiny?

> TODO: Perhaps autosave in the present working directory? 

Not clear.  Do we want to make it like chess, where touching a piece
means you have to move it?  In other words, not allow tentative changes
to the picture without having to record the tentative change?

Norm

**Comment by tehalexf** [comment]
Shiny: I redid some of the changes I did to the shiny interface (broke a few things by converting to R6), and will have something workable to push by Monday morning.

Autosave: My intention is more for preservation -- in case the Shiny app/modification function crashes, I'd like to have the current state of the modified image be saved. 

What you brought up is interesting though -- I think all changes can be tentative and recorded (you can make a change and undo it, and if you choose to make another change, the first change is now erased) -- there should definitely be some function called "finalize" or something similar that spits out a way for anyone else to duplicate the same changes to an image. 

In the case you describe, every change is already recorded and accessible: 
a= shinyimg$new(image) 
a$img_history # Will print out a list of all changes so far.

(which reminds me -- I need to make some fields of each object private).

Alex
